server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  application:
    name: Alloc

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

mail:
  appName: ALLOC

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml


notification:
  sqs:
    queue-name: ${NOTIFICATION_SQS_QUEUE_NAME:alloc-notification}

auth:
  cookie:
    access-token-name: accessToken
    refresh-token-name: refreshToken
    csrf-token-name: csrfToken
    same-site: Lax
    secure: false
    path: /
  sync:
    base-url: ${AUTH_SYNC_BASE_URL:http://moirai-auth-service:8082}

#ALB 헬스체크용
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

opensearch:
  host: ${OPENSEARCH_HOST:localhost}
  port: ${OPENSEARCH_PORT:9200}
  scheme: ${OPENSEARCH_SCHEME:http}
  username: ${OPENSEARCH_USERNAME:admin}
  password: ${OPENSEARCH_PASSWORD:Zp8$Lr@4X!sM29}
  ssl:
    enabled: ${OPENSEARCH_SSL_ENABLED:false}
    trustAll: ${OPENSEARCH_SSL_TRUST_ALL:false}
openai:
  api-key: ${OPENAI_API_KEY}