server:
  port: 8080

spring:
  profiles:
    active: local

  application:
    name: Alloc

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mariadb://localhost:3307/alloc
    username: alloc
    password: alloc
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

jwt:
  secret: Y9kA2ruWYaW5U2pw9awsYsA6VaK/6cGXPZqfIjjSihw=
  access-exp: 500       # 초
  refresh-exp: 12000    # 초
